### ISSUE TITLE
Add a counting number in (or near) each option.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/mozartDiceGame#10]
Exhibition visitors will be throwing two actual dice, calculating their sum, and selecting the option with that number.

Obviously, that the sum will be between 2 and 12 (total of 11 options).

We should provide each option with a counting number, as follows:

```
  2    3     4    5     6
7   8     9    10    11    12 
```

**Comment by XinyiDyee** [comment]
<img width="1404" alt="Screenshot 2024-09-09 at 16 03 05" src="https://github.com/user-attachments/assets/97e50e7a-fb5b-406e-9373-f13edfbf28e4">
The numbers are added

**Comment by yrammos** [comment]
Great, thanks @XinyiDyee. Closing this one.
