### ISSUE TITLE
Investigate cropped-off audio beginnings when selecting arbitrary measures.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/mozartDiceGame#2]
The first melody note, I think, is cropped off when selecting measures in the following view.

![Screenshot 2024-09-06 at 14 39 17](https://github.com/user-attachments/assets/9a8415f5-3460-4718-acc7-9539f7058853)

The issue does not exist when playing back the full phrase.

**Comment by XinyiDyee** [comment]
app.gameModel.samplePlayer.start(Tone.now(), 1.6); // starts with 2 second offset

I changed this line to set 1.6 second offset and the first melody notes become clear.

**Comment by XinyiDyee** [comment]
`app.gameModel.samplePlayer.start(Tone.now(), 1.6); // starts with 2 second offset
`
I changed this line in GameView.js to set 1.6 second offset and the first melody notes become clear.

**Comment by yrammos** [comment]
Excellent — confirming resolution, closing the issue.
