### ISSUE TITLE
Eliminate gaps between measures when playing the full phrase.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/mozartDiceGame#3]
A few milliseconds of silence seem to be inserted between measures when playing back the full (assembled) phrase. What is the cause of this delay? Could it be eliminated?

**Comment by yrammos** [comment]
The delay may be caused by a dependency. If eliminating it requires architectural changes to the app, we may need to close this issue unresolved.

**Comment by XinyiDyee** [comment]
resetSong() {
        Tone.Transport.position = '0:02:05';
    }
    
I set the start time at 0:02:05. I feel that the gap has been shortened through my own listening, and there is no long delay feeling. However, when I enter the web to play music for the first time, the delay time is not changed.

**Comment by yrammos** [comment]
Thanks for investigating, @XinyiDyee. The delay is shorter, and probably at acceptable levels, if not entirely eradicated.

Two quick questions:

1. What is the purpose of the lines you cite above? (And what’s special about the value `0:02:05`?)
2. What is the root cause of the delay?

**Comment by yrammos** [comment]
These questions aside, we may close this issue. Thanks.
