### ISSUE TITLE
Simplify interactions / make use more intuitive.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/mozartDiceGame#4]
- For example, not having to press "Exit" after selecting a measure.
		- "Flashing" the border of the just changed measure.
		- etc.

Let’s keep changes to a minimum, prioritizing stability and minimizing the risk of bug given the narrow time frame.

**Comment by yrammos** [comment]
@XinyiDyee this are meaningful improvements, thanks. A couple of comments:

1. Could we show the number of the affected measure in the "Confirm" button (e.g. "Confirm measure 3").
2. Newly selected options do not have a white background unless the user stops hovering on that option. To my eyes, this is confusing. Could we tweak the CSS, so that the white background appears on click (just before audio playback)?

**Comment by yrammos** [comment]
~~3. Do we actually need that "Confirm" button? Arguably not—it could be replaced by a simple informative message ("Select option for measure X").~~

**Comment by yrammos** [comment]
UPDATE: As you rightly said on Mattermost, we do need that "Confirm" button. Not all users are able to imagine the music when reading the notation.

**Comment by yrammos** [comment]
3. I like the disappearing measures when new content is selected. It would be more intuitive, I think, if we replaced that blank with a large question mark "?"—or even better, dynamically with the newly selected measure (as a preview of sorts). What do you think?

**Comment by XinyiDyee** [comment]
<img width="1413" alt="Screenshot 2024-09-09 at 20 27 55" src="https://github.com/user-attachments/assets/4accda3a-f944-4a88-8dc1-0529668f3328">
1. The number of the affected measure now is showed on the "confirm" button. <br>
2. The minuet button can change its background color to white when clicked, even when hovered. <br>
3. The background image of each slot can now change dynamically according to the selected minuet. I use images with opacity for better contrast to mark "?". When we click on a slot, the disappearing effect is also replaced by the original measure with opacity for consistency. <br>

**Comment by yrammos** [comment]
After ef3ee2f and cf4843e the behavior is exactly as planned. Thank you, @XinyiDyee. Closing for now, will report back in case of any new observations.
