### ISSUE TITLE
Initial "Enter" modal screen does not always appear on startup.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/mozartDiceGame#9]
A useful "Enter" modal appears on app startup under certain (currently unspecified) conditions.

The modal does not only improve the user experience, but also eradicates the initial playback delay.

I have investigated the conditions under which the modal appears. So far I have only obtained it using Firefox Developer Edition and selecting "iPad" as device in the browser inspector. See screenshot below.

![Screenshot 2024-09-09 at 11 20 36](https://github.com/user-attachments/assets/4d191ed1-e39a-4ba4-9df4-6b4fa65cdd21)

@XinyiDyee can we ensure that the modal appears in all cases?

**Comment by XinyiDyee** [comment]
I modified the GameModel file and removed the condition for device detection, making the code effective for all devices.

**Comment by yrammos** [comment]
This seems to work, thank you @XinyiDyee. Closing.
